[package]
name = "hwp-types"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-Proprietary"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11"
thiserror = "2.0.17"

[dev-dependencies]
serde_json = "1.0"